### ISSUE TITLE
Vulnerability

### ISSUE THREAD

**Issue by disser4** [shield-of-david/shield-of-david-releases#1]
Can you demonstrate how this is safe and not accidentally stealing any data from my machine?

**Comment by itaiperi** [comment]
Hi disser,
We're keeping this extension as a closed-source one, so I can't actually share the code for you to see.
I'd be happy to share with you the permissions we're currently asking for, from the extension's manifest file:
```
host_permissions: [
    "https://*.google.com/*",
    "https://app.posthog.com/"
  ]
...
permissions: ['alarms', 'tabs', 'storage', 'windows', 'webRequest']
```

And you don't have to take my word for it, you can see it for yourself in the `manifest.json` file that is in the main directory, after extracting the zip file.

We're working on getting this on the Chrome Web Store, but it's taking a bit of time.

I can assure you that no personal information is collected, and other than performing actions on your behalf in Twitter (reporting accounts), nothing else is done.
We do send minimal analytics so that we can know the number of users using the extension, but nothing more.

**Comment by disser4** [comment]
Thank you. I'll close the Issue.
